
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/JetBrains/CLion 2023.2.2/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineSystem.cmake:233 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The system is: Windows - 10.0.19045 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/JetBrains/CLion 2023.2.2/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/JetBrains/CLion 2023.2.2/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/JetBrains/CLion 2023.2.2/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler:  
      Build flags: 
      Id flags:  
      
      The output was:
      0
      Versi├│n de MSBuild 17.11.2+c078802d4 para .NET Framework
      Compilaci├│n iniciada a las 09/11/2024 16:18:49.
      
      Proyecto "D:\\Algoritmos y Estructura de Datos(AED)\\TAREASFML\\cmake-build-release-sfml\\CMakeFiles\\3.28.1\\CompilerIdC\\CompilerIdC.vcxproj" en nodo 1 (destinos predeterminados).
      PrepareForBuild:
        Creando directorio "Debug\\".
        La salida estructurada est├í habilitada. El formato del diagn├│stico del compilador reflejar├í la jerarqu├¡a de errores. Consulte https://aka.ms/cpp/structured-output para obtener m├ís detalles.
        Creando directorio "Debug\\CompilerIdC.tlog\\".
      InitializeBuildStatus:
        Se crear├í "Debug\\CompilerIdC.tlog\\unsuccessfulbuild" porque se especific├│ "AlwaysCreate".
        Aplicando tarea Touch a "Debug\\CompilerIdC.tlog\\unsuccessfulbuild".
      ClCompile:
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.41.34120\\bin\\HostX64\\x64\\CL.exe /c /nologo /W0 /WX- /diagnostics:column /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc143.pdb" /external:W0 /Gd /TC /FC /errorReport:queue CMakeCCompilerId.c
        CMakeCCompilerId.c
      Link:
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.41.34120\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdC.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdC.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdC.lib" /MACHINE:X64 Debug\\CMakeCCompilerId.obj
        CompilerIdC.vcxproj -> D:\\Algoritmos y Estructura de Datos(AED)\\TAREASFML\\cmake-build-release-sfml\\CMakeFiles\\3.28.1\\CompilerIdC\\CompilerIdC.exe
      PostBuildEvent:
        for %%i in (cl.exe) do @echo CMAKE_C_COMPILER=%%~$PATH:i
        :VCEnd
        CMAKE_C_COMPILER=C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.41.34120\\bin\\Hostx64\\x64\\cl.exe
      FinalizeBuildStatus:
        Se eliminar├í el archivo "Debug\\CompilerIdC.tlog\\unsuccessfulbuild".
        Aplicando tarea Touch a "Debug\\CompilerIdC.tlog\\CompilerIdC.lastbuildstate".
      Compilaci├│n del proyecto terminada "D:\\Algoritmos y Estructura de Datos(AED)\\TAREASFML\\cmake-build-release-sfml\\CMakeFiles\\3.28.1\\CompilerIdC\\CompilerIdC.vcxproj" (destinos predeterminados).
      
      Compilaci├│n correcta.
          0 Advertencia(s)
          0 Errores
      
      Tiempo transcurrido 00:00:01.46
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.exe"
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.vcxproj"
      
      The C compiler identification is MSVC, found in:
        D:/Algoritmos y Estructura de Datos(AED)/TAREASFML/cmake-build-release-sfml/CMakeFiles/3.28.1/CompilerIdC/CompilerIdC.exe
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/JetBrains/CLion 2023.2.2/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/JetBrains/CLion 2023.2.2/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/JetBrains/CLion 2023.2.2/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler:  
      Build flags: 
      Id flags:  
      
      The output was:
      0
      Versi├│n de MSBuild 17.11.2+c078802d4 para .NET Framework
      Compilaci├│n iniciada a las 09/11/2024 16:18:51.
      
      Proyecto "D:\\Algoritmos y Estructura de Datos(AED)\\TAREASFML\\cmake-build-release-sfml\\CMakeFiles\\3.28.1\\CompilerIdCXX\\CompilerIdCXX.vcxproj" en nodo 1 (destinos predeterminados).
      PrepareForBuild:
        Creando directorio "Debug\\".
        La salida estructurada est├í habilitada. El formato del diagn├│stico del compilador reflejar├í la jerarqu├¡a de errores. Consulte https://aka.ms/cpp/structured-output para obtener m├ís detalles.
        Creando directorio "Debug\\CompilerIdCXX.tlog\\".
      InitializeBuildStatus:
        Se crear├í "Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild" porque se especific├│ "AlwaysCreate".
        Aplicando tarea Touch a "Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild".
      ClCompile:
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.41.34120\\bin\\HostX64\\x64\\CL.exe /c /nologo /W0 /WX- /diagnostics:column /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc143.pdb" /external:W0 /Gd /TP /FC /errorReport:queue CMakeCXXCompilerId.cpp
        CMakeCXXCompilerId.cpp
      Link:
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.41.34120\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdCXX.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdCXX.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdCXX.lib" /MACHINE:X64 Debug\\CMakeCXXCompilerId.obj
        CompilerIdCXX.vcxproj -> D:\\Algoritmos y Estructura de Datos(AED)\\TAREASFML\\cmake-build-release-sfml\\CMakeFiles\\3.28.1\\CompilerIdCXX\\CompilerIdCXX.exe
      PostBuildEvent:
        for %%i in (cl.exe) do @echo CMAKE_CXX_COMPILER=%%~$PATH:i
        :VCEnd
        CMAKE_CXX_COMPILER=C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.41.34120\\bin\\Hostx64\\x64\\cl.exe
      FinalizeBuildStatus:
        Se eliminar├í el archivo "Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild".
        Aplicando tarea Touch a "Debug\\CompilerIdCXX.tlog\\CompilerIdCXX.lastbuildstate".
      Compilaci├│n del proyecto terminada "D:\\Algoritmos y Estructura de Datos(AED)\\TAREASFML\\cmake-build-release-sfml\\CMakeFiles\\3.28.1\\CompilerIdCXX\\CompilerIdCXX.vcxproj" (destinos predeterminados).
      
      Compilaci├│n correcta.
          0 Advertencia(s)
          0 Errores
      
      Tiempo transcurrido 00:00:00.80
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.exe"
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.vcxproj"
      
      The CXX compiler identification is MSVC, found in:
        D:/Algoritmos y Estructura de Datos(AED)/TAREASFML/cmake-build-release-sfml/CMakeFiles/3.28.1/CompilerIdCXX/CompilerIdCXX.exe
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Program Files/JetBrains/CLion 2023.2.2/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "C:/Program Files/JetBrains/CLion 2023.2.2/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:2 (project)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "D:/Algoritmos y Estructura de Datos(AED)/TAREASFML/cmake-build-release-sfml/CMakeFiles/CMakeScratch/TryCompile-nqgbje"
      binary: "D:/Algoritmos y Estructura de Datos(AED)/TAREASFML/cmake-build-release-sfml/CMakeFiles/CMakeScratch/TryCompile-nqgbje"
    cmakeVariables:
      CMAKE_C_FLAGS: "/DWIN32 /D_WINDOWS"
      CMAKE_C_FLAGS_DEBUG: "/Ob0 /Od /RTC1"
      CMAKE_EXE_LINKER_FLAGS: "/machine:x64"
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'D:/Algoritmos y Estructura de Datos(AED)/TAREASFML/cmake-build-release-sfml/CMakeFiles/CMakeScratch/TryCompile-nqgbje'
        
        Run Build Command(s): "C:/Program Files/Microsoft Visual Studio/2022/Community/MSBuild/Current/Bin/amd64/MSBuild.exe" cmTC_3d455.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=17.0 /v:n
        Versi├│n de MSBuild 17.11.2+c078802d4 para .NET Framework
        Compilaci├│n iniciada a las 09/11/2024 16:18:52.
        
        Proyecto "D:\\Algoritmos y Estructura de Datos(AED)\\TAREASFML\\cmake-build-release-sfml\\CMakeFiles\\CMakeScratch\\TryCompile-nqgbje\\cmTC_3d455.vcxproj" en nodo 1 (destinos predeterminados).
        PrepareForBuild:
          Creando directorio "cmTC_3d455.dir\\Debug\\".
          La salida estructurada est├í habilitada. El formato del diagn├│stico del compilador reflejar├í la jerarqu├¡a de errores. Consulte https://aka.ms/cpp/structured-output para obtener m├ís detalles.
          Creando directorio "D:\\Algoritmos y Estructura de Datos(AED)\\TAREASFML\\cmake-build-release-sfml\\CMakeFiles\\CMakeScratch\\TryCompile-nqgbje\\Debug\\".
          Creando directorio "cmTC_3d455.dir\\Debug\\cmTC_3d455.tlog\\".
        InitializeBuildStatus:
          Se crear├í "cmTC_3d455.dir\\Debug\\cmTC_3d455.tlog\\unsuccessfulbuild" porque se especific├│ "AlwaysCreate".
          Aplicando tarea Touch a "cmTC_3d455.dir\\Debug\\cmTC_3d455.tlog\\unsuccessfulbuild".
        ClCompile:
          C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.41.34120\\bin\\HostX64\\x64\\CL.exe /c /Zi /W1 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_3d455.dir\\Debug\\\\" /Fd"cmTC_3d455.dir\\Debug\\vc143.pdb" /external:W1 /Gd /TC /errorReport:queue "C:\\Program Files\\JetBrains\\CLion 2023.2.2\\bin\\cmake\\win\\x64\\share\\cmake-3.28\\Modules\\CMakeCCompilerABI.c"
          Compilador de optimizaci├│n de C/C++ de Microsoft (R) versi├│n 19.41.34120 para x64
          (C) Microsoft Corporation. Todos los derechos reservados.
          cl /c /Zi /W1 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_3d455.dir\\Debug\\\\" /Fd"cmTC_3d455.dir\\Debug\\vc143.pdb" /external:W1 /Gd /TC /errorReport:queue "C:\\Program Files\\JetBrains\\CLion 2023.2.2\\bin\\cmake\\win\\x64\\share\\cmake-3.28\\Modules\\CMakeCCompilerABI.c"
          CMakeCCompilerABI.c
        Link:
          C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.41.34120\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:"D:\\Algoritmos y Estructura de Datos(AED)\\TAREASFML\\cmake-build-release-sfml\\CMakeFiles\\CMakeScratch\\TryCompile-nqgbje\\Debug\\cmTC_3d455.exe" /INCREMENTAL /ILK:"cmTC_3d455.dir\\Debug\\cmTC_3d455.ilk" /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"D:/Algoritmos y Estructura de Datos(AED)/TAREASFML/cmake-build-release-sfml/CMakeFiles/CMakeScratch/TryCompile-nqgbje/Debug/cmTC_3d455.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"D:/Algoritmos y Estructura de Datos(AED)/TAREASFML/cmake-build-release-sfml/CMakeFiles/CMakeScratch/TryCompile-nqgbje/Debug/cmTC_3d455.lib" /MACHINE:X64  /machine:x64 cmTC_3d455.dir\\Debug\\CMakeCCompilerABI.obj
          cmTC_3d455.vcxproj -> D:\\Algoritmos y Estructura de Datos(AED)\\TAREASFML\\cmake-build-release-sfml\\CMakeFiles\\CMakeScratch\\TryCompile-nqgbje\\Debug\\cmTC_3d455.exe
        FinalizeBuildStatus:
          Se eliminar├í el archivo "cmTC_3d455.dir\\Debug\\cmTC_3d455.tlog\\unsuccessfulbuild".
          Aplicando tarea Touch a "cmTC_3d455.dir\\Debug\\cmTC_3d455.tlog\\cmTC_3d455.lastbuildstate".
        Compilaci├│n del proyecto terminada "D:\\Algoritmos y Estructura de Datos(AED)\\TAREASFML\\cmake-build-release-sfml\\CMakeFiles\\CMakeScratch\\TryCompile-nqgbje\\cmTC_3d455.vcxproj" (destinos predeterminados).
        
        Compilaci├│n correcta.
            0 Advertencia(s)
            0 Errores
        
        Tiempo transcurrido 00:00:00.75
        
      exitCode: 0
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Program Files/JetBrains/CLion 2023.2.2/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "C:/Program Files/JetBrains/CLion 2023.2.2/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:2 (project)"
    checks:
      - "Detecting CXX compiler ABI info"
    directories:
      source: "D:/Algoritmos y Estructura de Datos(AED)/TAREASFML/cmake-build-release-sfml/CMakeFiles/CMakeScratch/TryCompile-5r4oze"
      binary: "D:/Algoritmos y Estructura de Datos(AED)/TAREASFML/cmake-build-release-sfml/CMakeFiles/CMakeScratch/TryCompile-5r4oze"
    cmakeVariables:
      CMAKE_CXX_FLAGS: "/DWIN32 /D_WINDOWS /EHsc"
      CMAKE_CXX_FLAGS_DEBUG: "/Ob0 /Od /RTC1"
      CMAKE_EXE_LINKER_FLAGS: "/machine:x64"
    buildResult:
      variable: "CMAKE_CXX_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'D:/Algoritmos y Estructura de Datos(AED)/TAREASFML/cmake-build-release-sfml/CMakeFiles/CMakeScratch/TryCompile-5r4oze'
        
        Run Build Command(s): "C:/Program Files/Microsoft Visual Studio/2022/Community/MSBuild/Current/Bin/amd64/MSBuild.exe" cmTC_69cda.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=17.0 /v:n
        Versi├│n de MSBuild 17.11.2+c078802d4 para .NET Framework
        Compilaci├│n iniciada a las 09/11/2024 16:18:54.
        
        Proyecto "D:\\Algoritmos y Estructura de Datos(AED)\\TAREASFML\\cmake-build-release-sfml\\CMakeFiles\\CMakeScratch\\TryCompile-5r4oze\\cmTC_69cda.vcxproj" en nodo 1 (destinos predeterminados).
        PrepareForBuild:
          Creando directorio "cmTC_69cda.dir\\Debug\\".
          La salida estructurada est├í habilitada. El formato del diagn├│stico del compilador reflejar├í la jerarqu├¡a de errores. Consulte https://aka.ms/cpp/structured-output para obtener m├ís detalles.
          Creando directorio "D:\\Algoritmos y Estructura de Datos(AED)\\TAREASFML\\cmake-build-release-sfml\\CMakeFiles\\CMakeScratch\\TryCompile-5r4oze\\Debug\\".
          Creando directorio "cmTC_69cda.dir\\Debug\\cmTC_69cda.tlog\\".
        InitializeBuildStatus:
          Se crear├í "cmTC_69cda.dir\\Debug\\cmTC_69cda.tlog\\unsuccessfulbuild" porque se especific├│ "AlwaysCreate".
          Aplicando tarea Touch a "cmTC_69cda.dir\\Debug\\cmTC_69cda.tlog\\unsuccessfulbuild".
        ClCompile:
          C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.41.34120\\bin\\HostX64\\x64\\CL.exe /c /Zi /W1 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_69cda.dir\\Debug\\\\" /Fd"cmTC_69cda.dir\\Debug\\vc143.pdb" /external:W1 /Gd /TP /errorReport:queue "C:\\Program Files\\JetBrains\\CLion 2023.2.2\\bin\\cmake\\win\\x64\\share\\cmake-3.28\\Modules\\CMakeCXXCompilerABI.cpp"
          Compilador de optimizaci├│n de C/C++ de Microsoft (R) versi├│n 19.41.34120 para x64
          (C) Microsoft Corporation. Todos los derechos reservados.
          cl /c /Zi /W1 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_69cda.dir\\Debug\\\\" /Fd"cmTC_69cda.dir\\Debug\\vc143.pdb" /external:W1 /Gd /TP /errorReport:queue "C:\\Program Files\\JetBrains\\CLion 2023.2.2\\bin\\cmake\\win\\x64\\share\\cmake-3.28\\Modules\\CMakeCXXCompilerABI.cpp"
          CMakeCXXCompilerABI.cpp
        Link:
          C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.41.34120\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:"D:\\Algoritmos y Estructura de Datos(AED)\\TAREASFML\\cmake-build-release-sfml\\CMakeFiles\\CMakeScratch\\TryCompile-5r4oze\\Debug\\cmTC_69cda.exe" /INCREMENTAL /ILK:"cmTC_69cda.dir\\Debug\\cmTC_69cda.ilk" /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"D:/Algoritmos y Estructura de Datos(AED)/TAREASFML/cmake-build-release-sfml/CMakeFiles/CMakeScratch/TryCompile-5r4oze/Debug/cmTC_69cda.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"D:/Algoritmos y Estructura de Datos(AED)/TAREASFML/cmake-build-release-sfml/CMakeFiles/CMakeScratch/TryCompile-5r4oze/Debug/cmTC_69cda.lib" /MACHINE:X64  /machine:x64 cmTC_69cda.dir\\Debug\\CMakeCXXCompilerABI.obj
          cmTC_69cda.vcxproj -> D:\\Algoritmos y Estructura de Datos(AED)\\TAREASFML\\cmake-build-release-sfml\\CMakeFiles\\CMakeScratch\\TryCompile-5r4oze\\Debug\\cmTC_69cda.exe
        FinalizeBuildStatus:
          Se eliminar├í el archivo "cmTC_69cda.dir\\Debug\\cmTC_69cda.tlog\\unsuccessfulbuild".
          Aplicando tarea Touch a "cmTC_69cda.dir\\Debug\\cmTC_69cda.tlog\\cmTC_69cda.lastbuildstate".
        Compilaci├│n del proyecto terminada "D:\\Algoritmos y Estructura de Datos(AED)\\TAREASFML\\cmake-build-release-sfml\\CMakeFiles\\CMakeScratch\\TryCompile-5r4oze\\cmTC_69cda.vcxproj" (destinos predeterminados).
        
        Compilaci├│n correcta.
            0 Advertencia(s)
            0 Errores
        
        Tiempo transcurrido 00:00:00.80
        
      exitCode: 0
...
